# These are supported funding model platforms

github: edent # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: edent # Replace with a single Patreon username
open_collective: edent # Replace with a single Open Collective username
ko_fi: edent # Replace with a single Ko-fi username
custom: https://www.amazon.co.uk/hz/wishlist/ls/13GFCFR2B2IX4?tag=edentgithub-21
